theme: jekyll-theme-tactile
title: Peters Praktische PC-Tipps
description: Verschiedene aus dem Netz und Erfahrung zusammengetragene Tipps und Hinweise, die mir bei der Arbeit helfen und auch für andere nützlich sein könnten.
